agent-name: chutney-server-agent-0
server:
  port: 8350
  http:
    port: 9350
    interface: localhost
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

  servlet:
    session:
      cookie:
        http-only: true
        secure: true
      tracking-modes: cookie

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: '*'
        allowed-methods: GET
  endpoint:
    health:
      show-details: always

spring:
  liquibase:
    change-log: classpath:/changelog/db.changelog-master.xml
  profiles:
    active:
      - db-h2

chutney:
  configuration-folder: .chutney/conf
  environment:
    configuration-folder: ${chutney.configuration-folder}
  db-server:
    port: 9360
    base-dir: ./.chutney
  engine:
    reporter:
      publisher:
        ttl: 5
  execution:
    async:
      publisher:
        ttl: 5
        debounce: 250
  backups:
    root: backups
  examples:
    active: false

orient:
  path: .chutney/data/orient
  contextConfiguration:
    "[storage.diskCache.diskFreeSpaceLimit]": 384
    "[storage.diskCache.bufferSize]": 1024
